# Generated by Django 2.1.3 on 2018-12-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_bloguser_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='timestamp',
        ),
    ]
