# Generated by Django 2.1.3 on 2018-12-02 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_remove_bloguser_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
