# Generated by Django 2.1.3 on 2018-12-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_bloguser_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='username',
            new_name='usernames',
        ),
    ]
