# Generated by Django 2.1.3 on 2018-12-28 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_auto_20181202_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='telephone',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
